import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Assignment Module 11',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-10'>
        <Navbar />
        </div>
        <div className='p-10'>
        <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
